require:
  - rubocop-rails
  - rubocop-rspec
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  CacheRootDirectory: /tmp
RSpec/MultipleExpectations:
  Max: 2

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'db/**/*'
Metrics/AbcSize:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'db/**/*'
Layout/LineLength:
  Exclude:
    - 'db/**/*'
Metrics/BlockLength:
  Exclude:
    - 'db/**/*'