version: '3'
services:
  db:
    image: postgres:14.6
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build: .
    env_file: 
      - .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    user: "1000:1000"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle:
  db:
